### ISSUE TITLE
这个视频网站的视频是从别的网站爬的吗？

### ISSUE THREAD

**Issue by JssDream** [danbai225/dbys#1]
网站里面没有搜到庆余年？视频是怎么弄得
![image](https://user-images.githubusercontent.com/24471999/71331695-44419380-256e-11ea-8c22-8341cd375b3b.png)

**Comment by danbai225** [comment]
庆余年我下架了&nbsp; &nbsp;资源来自:http://www.okzy.co/&nbsp; &nbsp; 用py爬的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JssDream"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月23日(星期一) 上午10:23
收件人:&nbsp;"Programming-With-Love/dbys"<dbys@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Programming-With-Love/dbys] 这个视频网站的视频是从别的网站爬的吗？ (#1)




网站里面没有搜到庆余年？视频是怎么弄得
