### ISSUE TITLE
大佬，这个样式打不开了

### ISSUE THREAD

**Issue by yaoke602** [danbai225/dbys#16]
https://cdn.p00q.cn/ys/css/css2.css

**Comment by danbai225** [comment]
我也丢了没有了。。







------------------ 原始邮件 ------------------

发 件 人：yaoke602 ***@***.***>

发送时间：2024-01-26 23:34:48

收 件 人：Programming-With-Love/dbys ***@***.***>

抄 送：Subscribed ***@***.***>

主 题：[Programming-With-Love/dbys] 大佬，这个样式打不开了 (Issue #16)







https://cdn.p00q.cn/ys/css/css2.css

**Comment by yaoke602** [comment]
好的，谢谢大佬，挺好的的项目，要是有样式就能正常看了，好遗憾
